src/main/java/com/me/modulocompras/PersonasController.java
package com.me.modulocompras;

import com.me.modulocompras.util.JsfUtil;
import com.me.modulocompras.util.JsfUtil.PersistAction;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@Named("personasController")
@SessionScoped
public class PersonasController implements Serializable {

    @EJB
    private com.me.modulocompras.PersonasFacade ejbFacade;
    private List<Personas> items = null;
    private Personas selected;

    public PersonasController() {
    }

    public Personas getSelected() {
        return selected;
    }

    public void setSelected(Personas selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private PersonasFacade getFacade() {
        return ejbFacade;
    }

    public Personas prepareCreate() {
        selected = new Personas();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("PersonasCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("PersonasUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("PersonasDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Personas> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Personas getPersonas(java.lang.Integer id) {
        return getFacade().find(id);
    }

    public List<Personas> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Personas> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Personas.class)
    public static class PersonasControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            PersonasController controller = (PersonasController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "personasController");
            return controller.getPersonas(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Personas) {
                Personas o = (Personas) object;
                return getStringKey(o.getIdPersona());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Personas.class.getName()});
                return null;
            }
        }

    }

}

src/main/webapp/personas/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="PersonasCreateDlg" widgetVar="PersonasCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreatePersonasTitle}">
            <h:form id="PersonasCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{personasController.selected != null}">
                        <p:outputLabel value="#{bundle.CreatePersonasLabel_idPersona}" for="idPersona" />
                        <p:inputText id="idPersona" value="#{personasController.selected.idPersona}" title="#{bundle.CreatePersonasTitle_idPersona}" required="true" requiredMessage="#{bundle.CreatePersonasRequiredMessage_idPersona}"/>
                        <p:outputLabel value="#{bundle.CreatePersonasLabel_numDocumento}" for="numDocumento" />
                        <p:inputText id="numDocumento" value="#{personasController.selected.numDocumento}" title="#{bundle.CreatePersonasTitle_numDocumento}" required="true" requiredMessage="#{bundle.CreatePersonasRequiredMessage_numDocumento}"/>
                        <p:outputLabel value="#{bundle.CreatePersonasLabel_nombres}" for="nombres" />
                        <p:inputText id="nombres" value="#{personasController.selected.nombres}" title="#{bundle.CreatePersonasTitle_nombres}" required="true" requiredMessage="#{bundle.CreatePersonasRequiredMessage_nombres}"/>
                        <p:outputLabel value="#{bundle.CreatePersonasLabel_direccion}" for="direccion" />
                        <p:inputText id="direccion" value="#{personasController.selected.direccion}" title="#{bundle.CreatePersonasTitle_direccion}" required="true" requiredMessage="#{bundle.CreatePersonasRequiredMessage_direccion}"/>
                        <p:outputLabel value="#{bundle.CreatePersonasLabel_telefono}" for="telefono" />
                        <p:inputText id="telefono" value="#{personasController.selected.telefono}" title="#{bundle.CreatePersonasTitle_telefono}" required="true" requiredMessage="#{bundle.CreatePersonasRequiredMessage_telefono}"/>
                        <p:outputLabel value="#{bundle.CreatePersonasLabel_email}" for="email" />
                        <p:inputText id="email" value="#{personasController.selected.email}" title="#{bundle.CreatePersonasTitle_email}" required="true" requiredMessage="#{bundle.CreatePersonasRequiredMessage_email}"/>
                        <p:outputLabel value="#{bundle.CreatePersonasLabel_tipoPersona}" for="tipoPersona" />
                       
                        <p:selectOneMenu id="tipoPersona" value="#{personasController.selected.tipoPersona}" style="width: 125px" required="true" requiredMessage="#{bundle.CreatePersonasRequiredMessage_tipoPersona}">
                        <f:selectItem itemLabel="Selecione uno" itemValue=""/>
                        <f:selectItem itemLabel="Proveedor" itemValue="Proveedor"/>
                        <f:selectItem itemLabel="Cliente" itemValue="Cliente"/>
                        <f:selectItem itemLabel="Funcionario" itemValue="Funcionario"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.CreatePersonasLabel_idTipoDocumento}" for="idTipoDocumento" />
                        <p:selectOneMenu id="idTipoDocumento" value="#{personasController.selected.idTipoDocumento}" required="true" requiredMessage="#{bundle.EditPersonasRequiredMessage_idTipoDocumento}">
                            <f:selectItems value="#{tipoDocumentosController.itemsAvailableSelectOne}"
                                           var="idTipoDocumentoItem"
                                           itemValue="#{idTipoDocumentoItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.CreatePersonasLabel_idCiudad}" for="idCiudad" />
                        <p:selectOneMenu id="idCiudad" value="#{personasController.selected.idCiudad}" >
                            <f:selectItems value="#{ciudadesController.itemsAvailableSelectOne}"
                                           var="idCiudadItem"
                                           itemValue="#{idCiudadItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{personasController.create}" value="#{bundle.Save}" update="display,:PersonasListForm:datalist,:growl" oncomplete="handleSubmit(args,'PersonasCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="PersonasCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

src/main/webapp/personas/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="PersonasEditDlg" widgetVar="PersonasEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditPersonasTitle}">
            <h:form id="PersonasEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{personasController.selected != null}">
                        <p:outputLabel value="#{bundle.EditPersonasLabel_idPersona}" for="idPersona" />
                        <p:inputText id="idPersona" value="#{personasController.selected.idPersona}" title="#{bundle.EditPersonasTitle_idPersona}" required="true" requiredMessage="#{bundle.EditPersonasRequiredMessage_idPersona}"/>
                        <p:outputLabel value="#{bundle.EditPersonasLabel_numDocumento}" for="numDocumento" />
                        <p:inputText id="numDocumento" value="#{personasController.selected.numDocumento}" title="#{bundle.EditPersonasTitle_numDocumento}" required="true" requiredMessage="#{bundle.EditPersonasRequiredMessage_numDocumento}"/>
                        <p:outputLabel value="#{bundle.EditPersonasLabel_nombres}" for="nombres" />
                        <p:inputText id="nombres" value="#{personasController.selected.nombres}" title="#{bundle.EditPersonasTitle_nombres}" required="true" requiredMessage="#{bundle.EditPersonasRequiredMessage_nombres}"/>
                        <p:outputLabel value="#{bundle.EditPersonasLabel_direccion}" for="direccion" />
                        <p:inputText id="direccion" value="#{personasController.selected.direccion}" title="#{bundle.EditPersonasTitle_direccion}" required="true" requiredMessage="#{bundle.EditPersonasRequiredMessage_direccion}"/>
                        <p:outputLabel value="#{bundle.EditPersonasLabel_telefono}" for="telefono" />
                        <p:inputText id="telefono" value="#{personasController.selected.telefono}" title="#{bundle.EditPersonasTitle_telefono}" required="true" requiredMessage="#{bundle.EditPersonasRequiredMessage_telefono}"/>
                        <p:outputLabel value="#{bundle.EditPersonasLabel_email}" for="email" />
                        <p:inputText id="email" value="#{personasController.selected.email}" title="#{bundle.EditPersonasTitle_email}" required="true" requiredMessage="#{bundle.EditPersonasRequiredMessage_email}"/>
                        <p:outputLabel value="#{bundle.EditPersonasLabel_tipoPersona}" for="tipoPersona" />
                        <p:inputText id="tipoPersona" value="#{personasController.selected.tipoPersona}" title="#{bundle.EditPersonasTitle_tipoPersona}" required="true" requiredMessage="#{bundle.EditPersonasRequiredMessage_tipoPersona}"/>
                        <p:outputLabel value="#{bundle.EditPersonasLabel_idTipoDocumento}" for="idTipoDocumento" />
                        <p:selectOneMenu id="idTipoDocumento" value="#{personasController.selected.idTipoDocumento}" required="true" requiredMessage="#{bundle.EditPersonasRequiredMessage_idTipoDocumento}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{tipoDocumentosController.itemsAvailableSelectOne}"
                                           var="idTipoDocumentoItem"
                                           itemValue="#{idTipoDocumentoItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.EditPersonasLabel_idCiudad}" for="idCiudad" />
                        <p:selectOneMenu id="idCiudad" value="#{personasController.selected.idCiudad}" >
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{ciudadesController.itemsAvailableSelectOne}"
                                           var="idCiudadItem"
                                           itemValue="#{idCiudadItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{personasController.update}" value="#{bundle.Save}" update="display,:PersonasListForm:datalist,:growl" oncomplete="handleSubmit(args, 'PersonasEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="PersonasEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

src/main/webapp/personas/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListPersonasTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="PersonasListForm">
                <p:panel header="#{bundle.ListPersonasTitle}">
                    <p:dataTable id="datalist" value="#{personasController.items}" var="item"
                                 selectionMode="single" selection="#{personasController.selected}"
                                 paginator="true"
                                 rowKey="#{item.idPersona}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPersonasTitle_idPersona}"/>
                            </f:facet>
                            <h:outputText value="#{item.idPersona}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPersonasTitle_numDocumento}"/>
                            </f:facet>
                            <h:outputText value="#{item.numDocumento}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPersonasTitle_nombres}"/>
                            </f:facet>
                            <h:outputText value="#{item.nombres}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPersonasTitle_direccion}"/>
                            </f:facet>
                            <h:outputText value="#{item.direccion}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPersonasTitle_telefono}"/>
                            </f:facet>
                            <h:outputText value="#{item.telefono}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPersonasTitle_email}"/>
                            </f:facet>
                            <h:outputText value="#{item.email}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPersonasTitle_tipoPersona}"/>
                            </f:facet>
                            <h:outputText value="#{item.tipoPersona}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPersonasTitle_idTipoDocumento}"/>
                            </f:facet>
                            <h:outputText value="#{item.idTipoDocumento}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPersonasTitle_idCiudad}"/>
                            </f:facet>
                            <h:outputText value="#{item.idCiudad}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{bundle.Create}" actionListener="#{personasController.prepareCreate}" update=":PersonasCreateForm" oncomplete="PF('PersonasCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle.View}" update=":PersonasViewForm" oncomplete="PF('PersonasViewDialog').show()" disabled="#{empty personasController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle.Edit}" update=":PersonasEditForm" oncomplete="PF('PersonasEditDialog').show()" disabled="#{empty personasController.selected}"/>
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{bundle.Delete}" actionListener="#{personasController.destroy}" update=":growl,datalist" disabled="#{empty personasController.selected}"/>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

src/main/webapp/personas/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="PersonasViewDlg" widgetVar="PersonasViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewPersonasTitle}">
            <h:form id="PersonasViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{personasController.selected != null}">
                        <h:outputText value="#{bundle.ViewPersonasLabel_idPersona}"/>
                        <h:outputText value="#{personasController.selected.idPersona}" title="#{bundle.ViewPersonasTitle_idPersona}"/>
                        <h:outputText value="#{bundle.ViewPersonasLabel_numDocumento}"/>
                        <h:outputText value="#{personasController.selected.numDocumento}" title="#{bundle.ViewPersonasTitle_numDocumento}"/>
                        <h:outputText value="#{bundle.ViewPersonasLabel_nombres}"/>
                        <h:outputText value="#{personasController.selected.nombres}" title="#{bundle.ViewPersonasTitle_nombres}"/>
                        <h:outputText value="#{bundle.ViewPersonasLabel_direccion}"/>
                        <h:outputText value="#{personasController.selected.direccion}" title="#{bundle.ViewPersonasTitle_direccion}"/>
                        <h:outputText value="#{bundle.ViewPersonasLabel_telefono}"/>
                        <h:outputText value="#{personasController.selected.telefono}" title="#{bundle.ViewPersonasTitle_telefono}"/>
                        <h:outputText value="#{bundle.ViewPersonasLabel_email}"/>
                        <h:outputText value="#{personasController.selected.email}" title="#{bundle.ViewPersonasTitle_email}"/>
                        <h:outputText value="#{bundle.ViewPersonasLabel_tipoPersona}"/>
                        <h:outputText value="#{personasController.selected.tipoPersona}" title="#{bundle.ViewPersonasTitle_tipoPersona}"/>
                        <h:outputText value="#{bundle.ViewPersonasLabel_idTipoDocumento}"/>
                        <h:outputText value="#{personasController.selected.idTipoDocumento}" title="#{bundle.ViewPersonasTitle_idTipoDocumento}"/>
                        <h:outputText value="#{bundle.ViewPersonasLabel_idCiudad}"/>
                        <h:outputText value="#{personasController.selected.idCiudad}" title="#{bundle.ViewPersonasTitle_idCiudad}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="PersonasViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>